"""Unified AI-stack key + endpoint resolver for Cyclops.

Reads the existing key store that the rest of the user's stack already
maintains:

  * /home/gio/ai_api.txt  -- auto-generated by nightly_update.py from .env
        format (one entry per line, comma-separated multiples allowed):
            gemini:KEY1,KEY2
            groq:https://api.groq.com/openai/v1   (endpoint: lines end in _endpoint)
  * ~/.env / /home/gio/.env  -- standard KEY=VALUE secrets

This module is intentionally dependency-free and side-effect free on import
so it is unit-testable with no network and no secrets present.

Usage:
    from brain.aikeys import AiKeys
    k = AiKeys()                       # autodiscover locations
    k.get_key("gemini")                # -> first gemini key or None
    k.get_endpoint("groq")             # -> url or None
    k.provider("groq")                 # -> {"key":..,"endpoint":..,"api_key":..}
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Iterable

DEFAULT_AI_API_TXT = "/home/gio/ai_api.txt"
DEFAULT_ENV_PATHS = ("~/.env", "/home/gio/.env", "/home/gio/ai_api.txt")


class AiKeys:
    def __init__(
        self,
        ai_api_txt: str | None = None,
        env_paths: Iterable[str] | None = None,
        oauth_store=None,
    ):
        self.ai_api_txt = ai_api_txt or os.environ.get(
            "CYCLOPS_AI_API_TXT", DEFAULT_AI_API_TXT
        )
        self.env_paths = (
            list(env_paths) if env_paths is not None else list(DEFAULT_ENV_PATHS)
        )
        # map name -> list[str] for keys, name -> endpoint str for endpoints
        self._keys: dict[str, list[str]] = {}
        self._endpoints: dict[str, str] = {}
        self._load_ai_api_txt()
        self._load_env()
        # OAuth device-flow providers (brain/oauth_store.py) are a second,
        # writable key source layered on top of the static .env/ai_api.txt
        # ones above -- injectable for tests, lazily constructed for real use
        # so importing this module never touches the filesystem on its own.
        self._oauth = oauth_store
        self._oauth_provider_cfgs = None  # loaded lazily, see _oauth_cfg()

    def _oauth_store(self):
        if self._oauth is None:
            from .oauth_store import OAuthStore

            self._oauth = OAuthStore()
        return self._oauth

    def _oauth_cfg(self, name: str):
        if self._oauth_provider_cfgs is None:
            from .oauth_store import load_provider_configs

            self._oauth_provider_cfgs = load_provider_configs()
        return self._oauth_provider_cfgs.get(name.lower())

    # ---------------------------------------------------------------- loading
    def _load_ai_api_txt(self):
        p = Path(self.ai_api_txt).expanduser()
        if not p.exists():
            return
        for raw in p.read_text(encoding="utf-8", errors="ignore").splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if ":" not in line:
                continue
            name, _, value = line.partition(":")
            name = name.strip().lower()
            value = value.strip()
            if name.endswith("_endpoint"):
                self._endpoints[name[: -len("_endpoint")]] = value
            else:
                # value may be a comma-separated list of keys
                for part in value.split(","):
                    part = part.strip()
                    if part:
                        self._keys.setdefault(name, []).append(part)

    def _load_env(self):
        for ep in self.env_paths:
            p = Path(ep).expanduser()
            if not p.exists() or p == Path(self.ai_api_txt).expanduser():
                continue
            for raw in p.read_text(encoding="utf-8", errors="ignore").splitlines():
                line = raw.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                name, _, value = line.partition("=")
                name = name.strip()
                value = value.strip().strip('"').strip("'")
                if not name or not value:
                    continue
                self._endpoints.setdefault(name.lower(), value)  # raw URL?
                # also register as a key source for *_API_KEY style names
                if re.search(r"API_KEY|TOKEN|SECRET|KEY", name, re.I):
                    self._keys.setdefault(name.lower(), []).append(value)

    # ---------------------------------------------------------------- access
    def get_key(self, name: str) -> str | None:
        """Return the first available key for `name` (provider-agnostic).
        Falls back to a valid (transparently-refreshed) OAuth device-flow
        token for `name` if no static key is configured."""
        keys = self._keys.get(name.lower())
        if keys:
            return keys[0]
        return self._oauth_store().get_valid_key(name.lower(), provider_cfg=self._oauth_cfg(name))

    def get_keys(self, name: str) -> list[str]:
        return list(self._keys.get(name.lower(), []))

    def get_endpoint(self, name: str) -> str | None:
        ep = self._endpoints.get(name.lower())
        if ep:
            return ep
        cfg = self._oauth_cfg(name)
        return cfg.api_base_url if cfg and cfg.api_base_url else None

    def has(self, name: str) -> bool:
        return bool(self.get_key(name) or self.get_endpoint(name))

    def provider(self, name: str) -> dict:
        """Return a normalized provider descriptor for `name`."""
        return {
            "name": name.lower(),
            "key": self.get_key(name),
            "api_key": self.get_key(name),
            "endpoint": self.get_endpoint(name),
        }

    def available(self) -> list[str]:
        """Names that have at least one key or endpoint (static or OAuth)."""
        names = set(self._keys) | set(self._endpoints) | set(self._oauth_store().available_providers())
        return sorted(n for n in names if self.has(n))

    def as_dict(self) -> dict:
        # never expose secret values outside the process; tests assert shape
        return {
            n: ("<set>" if self.has(n) else None)
            for n in sorted(set(self._keys) | set(self._endpoints))
        }
